# Generated by Django 5.0.7 on 2024-07-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childrenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryfees',
            name='secfeesAmount',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblings1',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblings2',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblings3',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblings4',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblingsRelationship1',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblingsRelationship2',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblingsRelationship3',
        ),
        migrations.RemoveField(
            model_name='siblings',
            name='siblingsRelationship4',
        ),
    ]
