# Generated by Django 5.0.7 on 2024-07-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenapp', '0002_remove_secondaryfees_secfeesamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siblings',
            name='siblings1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siblings',
            name='siblings2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siblings',
            name='siblings3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siblings',
            name='siblings4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siblings',
            name='siblingsRelationship1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siblings',
            name='siblingsRelationship2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siblings',
            name='siblingsRelationship3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siblings',
            name='siblingsRelationship4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
