# Generated by Django 5.0.7 on 2024-07-25 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenapp', '0005_alter_refund_refundapprovaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporary',
            name='temp_address1Line1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_address1Line2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_address1PostalCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_address1Transport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childAge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childBirthID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childCitizenship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childDOB',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childForeignName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childGender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childHouseholdIncome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childMTLanguage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childRace',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childReligion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childResidentialRemarks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childResidentialStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childSubsidyType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_childToStaff',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_emergency1Email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_emergency1Mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_emergency1Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_emergency1Phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_emergency1Relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_fatherAddBlock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_fatherAddBuilding',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_fatherAddPostalCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_fatherAddStreet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_fatherAddTransport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_fatherAddUnit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_healthAllergy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_healthFamDrNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_healthMedCon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_healthSpecialDiet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_healthSpecialNeeds',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_healthVaccination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_motherAddBlock',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_motherAddBuilding',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_motherAddPostalCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_motherAddStreet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_motherAddTransport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_motherAddUnit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1AuthorisedPickUp',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Citizenship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1EmailCheckIn',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1EmailInvoiceReceipt',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1ID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1MainContact',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent1Relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2AuthorisedPickUp',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Citizenship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2EmailCheckIn',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2EmailInvoiceReceipt',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2ID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2MainContact',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent2Relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3AuthorisedPickUp',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Citizenship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3EmailCheckIn',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3EmailInvoiceReceipt',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3ID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3MainContact',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_parent3Relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prieesPaymentMethod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesAmount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesApprovalDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesAttentionTo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesBankAccCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesBankAccHolder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesBankAccNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesBankName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesBranchCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_prifeesPayeeID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundApprovalDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundApprovalReference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundBankAccCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundBankAccHolder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundBankAccNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundBankName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundBranchCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundDepositOpt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_refundPaymentMethod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_schoolAdmissionDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_schoolClassLevel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_schoolClassSession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_schoolClassname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_schoolProgramType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_schoolTransportationNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_schoolWithdrawalDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesApprovalDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesAttentionTo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesBankAccCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesBankAccHolder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesBankAccNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesBankName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesBranchCode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesPayeeID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_secfeesPaymentMethod',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblings1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblings2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblings3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblings4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblingsRelationship1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblingsRelationship2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblingsRelationship3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporary',
            name='temp_siblingsRelationship4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='child',
            name='childDOB',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='secondaryfees',
            name='secfeesApprovalDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempAddress',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.address'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempChild',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.child'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempEmergency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.emergency'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempFatherAdd',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.fatheradd'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempHealth',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.health'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempMotherAdd',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.motheradd'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempParent1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.parent1'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempParent2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.parent2'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempParent3',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.parent3'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempPrimaryFees',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.primaryfees'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempRefund',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.refund'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempSchool',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.school'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempSecondaryFees',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.secondaryfees'),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='tempSiblings',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.siblings'),
        ),
        migrations.CreateModel(
            name='CoreServiceFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=250)),
                ('firstName', models.CharField(blank=True, max_length=250)),
                ('lastName', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(blank=True, max_length=250)),
                ('gender', models.CharField(blank=True, max_length=250)),
                ('birthIC', models.CharField(blank=True, max_length=250)),
                ('birthCountry', models.CharField(blank=True, max_length=250)),
                ('occupation', models.CharField(blank=True, max_length=250)),
                ('relationship', models.CharField(blank=True, max_length=250)),
                ('profileImage', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('postcode', models.CharField(blank=True, max_length=250)),
                ('isArchived', models.CharField(blank=True, max_length=250)),
                ('isAllowPickup', models.CharField(blank=True, max_length=250)),
                ('isEmergencyContact', models.CharField(blank=True, max_length=250)),
                ('isBillable', models.CharField(blank=True, max_length=250)),
                ('isPrimary', models.CharField(blank=True, max_length=250)),
                ('isWebAccess', models.CharField(blank=True, max_length=250)),
                ('isMobileAccess', models.CharField(blank=True, max_length=250)),
                ('creator', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('CSFamFatherAdd', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.fatheradd')),
                ('CSFamMotherAdd', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.motheradd')),
                ('CSFamParent1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.parent1')),
                ('CSFamParent2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.parent2')),
                ('CSFamParent3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.parent3')),
            ],
        ),
    ]
