# Generated by Django 5.0.7 on 2024-07-31 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenapp', '0006_temporary_temp_address1line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreservicefamily',
            name='CSFamFatherAdd',
        ),
        migrations.RemoveField(
            model_name='coreservicefamily',
            name='CSFamMotherAdd',
        ),
        migrations.RemoveField(
            model_name='coreservicefamily',
            name='CSFamParent1',
        ),
        migrations.RemoveField(
            model_name='coreservicefamily',
            name='CSFamParent2',
        ),
        migrations.RemoveField(
            model_name='coreservicefamily',
            name='CSFamParent3',
        ),
        migrations.AddField(
            model_name='coreservicefamily',
            name='CSFChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.child'),
        ),
        migrations.AddField(
            model_name='coreservicefamily',
            name='CSFTemporary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.temporary'),
        ),
    ]
