# Generated by Django 5.0.7 on 2024-08-09 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenapp', '0007_remove_coreservicefamily_csfamfatheradd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreServiceChildrenMedicalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=250)),
                ('contactType', models.CharField(blank=True, max_length=250)),
                ('specialtyType', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=250)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('state', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(blank=True, max_length=250)),
                ('postcode', models.CharField(blank=True, max_length=250)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('enterBy', models.CharField(blank=True, max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='updatedAt')),
                ('child_id', models.CharField(blank=True, max_length=250)),
                ('isArchived', models.CharField(blank=True, max_length=250)),
                ('CSCMCChild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.child')),
                ('CSCMCTemporary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='childrenapp.temporary')),
            ],
        ),
    ]
