# Generated by Django 5.0.7 on 2024-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenapp', '0008_coreservicechildrenmedicalcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(blank=True, max_length=250)),
                ('staff_email', models.CharField(blank=True, max_length=250)),
                ('staff_gender', models.CharField(blank=True, max_length=250)),
                ('staff_dob', models.CharField(blank=True, max_length=250)),
                ('staff_title', models.CharField(blank=True, max_length=250)),
                ('staff_mobileNum', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
