# Generated by Django 5.0.7 on 2024-08-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childrenapp', '0009_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryfees',
            name='prieesPaymentMethod',
        ),
        migrations.AddField(
            model_name='primaryfees',
            name='prifeesPaymentMethod',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
