# Generated by Django 5.0.7 on 2024-07-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchId', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=100)),
                ('birthIC', models.CharField(max_length=12)),
                ('birthDate', models.DateField()),
                ('birthCountry', models.CharField(max_length=50)),
                ('ethnicity', models.CharField(choices=[('Malay', 'Malay'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Others', 'Others')], max_length=50)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Others', 'Others')], max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergyType', models.CharField(max_length=30)),
                ('allergies', models.CharField(max_length=30)),
                ('allergicPrevent', models.CharField(max_length=30)),
                ('allergicSyndrome', models.CharField(max_length=30)),
                ('allergicAction', models.CharField(max_length=30)),
                ('haveMedicine', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.children')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNameFamily', models.CharField(max_length=50)),
                ('lastNameFamily', models.CharField(max_length=50)),
                ('phoneFamily', models.CharField(max_length=15)),
                ('emailFamily', models.CharField(max_length=50)),
                ('birthICFamily', models.CharField(max_length=12)),
                ('birthCountryFamily', models.CharField(max_length=30)),
                ('occupationFamily', models.CharField(max_length=20)),
                ('relationshipFamily', models.CharField(max_length=20)),
                ('addressFamily', models.CharField(max_length=100)),
                ('stateFamily', models.CharField(max_length=50)),
                ('countryFamily', models.CharField(max_length=50)),
                ('postcodeFamily', models.CharField(max_length=10)),
                ('isAllowPickup', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.children')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactTypeMC', models.CharField(max_length=50)),
                ('specialtyTypeMC', models.CharField(max_length=50)),
                ('nameMC', models.CharField(max_length=50)),
                ('phoneMC', models.CharField(max_length=15)),
                ('addressMC', models.CharField(max_length=100)),
                ('stateMC', models.CharField(max_length=50)),
                ('countryMC', models.CharField(max_length=50)),
                ('postcodeMC', models.CharField(max_length=10)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.children')),
            ],
        ),
    ]
